### ISSUE TITLE
Load file error: path corrupt

### ISSUE THREAD

**Issue by SolarDaniel** [project-chip/zap#1019]
Looks like a bug??
Anyone using it on Windows?

Using Windows 10
Installed latest zap tool in  'C:\NRFSDK\zap'
Installed latest node.js 20.1.0 (also tried 16.13.2 as mentioned in install instructions), just to be shure it's not a node.js problem.
start: double click zap.exe in installed directory (also tried as admin)
File->Open File: select weather-station.zap, that resides in zap install directory
ENOENT: no such file or directory, open '**C:\NRFSDK\zap\NRFSDKzapweather-station.zap**'
![image](https://github.com/project-chip/zap/assets/38322666/dca34080-94a3-49fb-9048-48a931dabde7)

When placing the file in 'c:\\' it loads correctly
![image](https://github.com/project-chip/zap/assets/38322666/8434d556-fc32-45c5-ba58-3140da2e1fac)

Saving the file ignores the choosen path, stores it in zap install directory
Generate... does nothing, without error message

Preview... shows nothing
![image](https://github.com/project-chip/zap/assets/38322666/9be0ff00-f09b-4ce0-a204-549085308907)

Please help

**Comment by brdandu** [comment]
I see that you have `NRFSDKzapweather-station.zap` instead of `weather-station` when it does not work. Wondering where is the additional `NRFSDKzap` coming from. May be it is prefixing the path again somehow.

When it works under C:\, Can you go to zcl extensions and see what is loaded? You will not have any generation unless there is a generation template file reference.
For saving what happens when you use `save as` ?
