### ISSUE TITLE
Device types seem to be pretty broken

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/zap#279]
It looks like in the database device types are attached to _endpoints_, not endpoint types.  Or at least endpoints have a DEVICE_IDENTIFIER that seems like an actual device id.

Endpoints types have a DEVICE_TYPE_ID, but that seems unrelated to what I select in the UI for the device type of an endpoint.

The `endpoint_fixed_device_id_array` seems to be examining `deviceList`, which was constructed based on the list of _endpoint types_, which is not what device ids are associated with?  So all of the things in there have 0 for `deviceId`, leading to https://github.com/project-chip/connectedhomeip/issues/6757

@tecimovic Am I just missing something in how this should work?

**Comment by tecimovic** [comment]
1.) DEVICE_TYPE table contains the CODE, which is the official "code" from the ZCL spec.
2.) Loader also loads a "custom device type", but ONLY if `zcl.json` says: `"supportCustomZclDevice": true`. So that's an SDK choice.
3.) The custom device type metainfo is hardcoded into db-enum.js:
```
exports.customDevice = {
  domain: 'Custom',
  name: 'Custom ZCL Device Type',
  description: 'Custom ZCL device type supports any combination of clusters.',
  code: 0xffff,
  profileId: 0xffff,
}

```
4.) ENDPOINT_TYPE must be associated with ONE device type via a foreign key. It can be a REAL device type, or a custom one, if that's available.

5.) Inside ENDPOINT table, there is an actual DEVICE_IDENTIFIER. That is the actual DEVICE_IDENTIFIER that will be used. User has an option to put there whatever number they want. There are some expectations though:
    a.) If the ENDPOINT_TYPE is linked to a non-custom device A, but a user decides to put in there value B, then that is a bit weird. I don't know why they would want to do that.
    b.) If the ENDPOINT_TYPE is linked to a custom device, then user is EXPECTED to put a non 0xFFFF value there, because 0xFFFF is not a valid device type according to Zigbee spec.

6.) I *think*, but this needs to be validate, that the UI should work like this:
    a.) If you select a valid device in the dropdown of endpoint editor, then you set BOTH the Device_type_id from endpoint_type AND the device_identifier in the endpoint table.
   b.) If you just type some random integer, which doesn't have an appropriate device code, it will update DEVICE_IDENTIFIER in the ENDPOINT table, but leave the ENDPOINT_TYPE linkage alone.


Overall:
   this difference between ENDPOINT_TYPE and ENDPOINT has been under much scrutiny and discussion in our Zigbee stack already. UI consultants have told us that it is confusing, and that users should be shielded from that. So to users it appears as if they simply create endpoints. Only in the schema is the concept of ENDPOINT_TYPE, and the ability to declare multiple ENDPOINTS that use same ENDPOINT_TYPE behind the hood.

**Comment by tecimovic** [comment]
Closed by mistake. I clicked the wrong button...

**Comment by bzbarsky-apple** [comment]
> Does Matter expect to support custom device type? Or do you force everyone to be one of the predefined device types at all times?

There are provisions for vendor-defined device types, I believe, so the former.

> Does Matter expect to support the idea that you have a separate ENDPOINT_TYPE

Right now we do support it, as a space optimization, right?  It seems like a useful one...

> Is Matter simply inheriting existing ZCL device types

Matter has a device type library which is based on the ZDL and is generally aimed to merge with the ZDL in the future, but is distinct for the moment.  It has different cluster requirements from the ZDL (e.g. Matter does NOT have a Basic cluster on endpoints other than endpoint 0).

Another big differenceis that Matter, unlike ZCL, allows attaching multiple device type ids to the same endpoint.

**Comment by leorozendaal** [comment]
>> Does Matter expect to support custom device type? Or do you force everyone to be one of the predefined device types at all times?
> There are provisions for vendor-defined device types, I believe, so the former.

Indeed, device type is 32 bits.
- If top 16 bits are 0x0000, it's a standard device type (lower 16 bits contain id from the device library)
- Otherwise, it's a vendor-defined device type with top 16 bits cotaining vendorid, , lower 16 bits contain device id (in vendor's identifier space)

**Comment by leorozendaal** [comment]
> Another big difference is that Matter, unlike ZCL, allows attaching multiple device type ids to the same endpoint.

Indeed, so the Descriptor cluster contains a LIST of devicetypestruct (which is device id + revision). This seems to be dearly missing from current SDK
