### ISSUE TITLE
Need support for specifying multiple device types for an endpoint

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/zap#366]
Needed to fix https://github.com/project-chip/connectedhomeip/issues/12418

**Comment by tecimovic** [comment]
@brdandu : @bzbarsky-apple just told me this has become more of a priority because of Bridge spec which requires it.
Question: did you do anything specific with this already, or it just sits in your backlog?

**Comment by tecimovic** [comment]
Just for the record:
   in appbuilder, the multiple device types were assentially implement as follows:
   
 1.) Adding a "device type" to endpoint meant making sure "mandatory" clusters are present and "prohibited" clusters are NOT.
 2.) If you added ANOTHER device type, that meant: adding more mandatory clusters and removing more prohibited clusters.
 3.) If you REMOVED a device type, that would essentially just remove prohibited clusters. We didn't really remove clusters that were NOT mandatory.
 4.) if you ended up in a weird state, where two device types that were added conflicted themselves (because same cluster was MANDATORY in one and PROHIBITED in another), there would be a lot of warnings in the UI, but so be it.
    
So in essence, multiple device types meant to simply aggregate the lists of PROHIBITED and MANDATORY and RECOMMENDED and POSSIBLE clusters and operate with that list.
It also remembered the list of device types, mostly so that UI could properly emit warnings if further work on the part of the user did anything weird to negate those.

**Comment by brdandu** [comment]
> @brdandu : @bzbarsky-apple just told me this has become more of a priority because of Bridge spec which requires it.
> Question: did you do anything specific with this already, or it just sits in your backlog?

I have not done anything related to the ZCL device types. I mistook this for data types. However I do have a lot of questions on why do we need this?
I see a bunch of issues with this. Are we saying an endpoint is somehow a union of ZCL device types? Is there a possibility that one ZCL device types configuration contradicts another ZCL device type? If so then what do we do for those contradictory configurations between multiple ZCL device types for an endpoint?

**Comment by leorozendaal** [comment]
@brdandu  Combining contradicting device types on an EP is forbidden 
Main use case for this multi-device type feature , see https://github.com/project-chip/connectedhomeip/issues/12418  and https://github.com/project-chip/connectedhomeip/issues/16686 . Those are non-contradicting device types

**Comment by bzbarsky-apple** [comment]
To be clear, the absolute must-have requirement here is for the database to support this, so Matter can emit endpoint metadata with multiple device types.

**Comment by leorozendaal** [comment]
SDK support implemented as of https://github.com/project-chip/connectedhomeip/pull/16880

**Comment by tecimovic** [comment]
Additional information: there is also support required for multiple SAME device types with different VERSIONS on the same endpoint.

**Comment by leorozendaal** [comment]
> Additional information: there is also support required for multiple SAME device types with different VERSIONS on the same endpoint.

Assuming the different versions of the device type have the same clusters, this would conflict with the spec.

Let's no put effort into configurations which are forbidden.

**Comment by tecimovic** [comment]
Ok, I'm confused....

@bzbarsky-apple : you mentioned that different versions of a device type on the same endpoint are supported.
@leorozendaal : you are saying the opposite.

Can you point me to the spec where this is listed?

**Comment by bzbarsky-apple** [comment]
@tecimovic Where did I say that?  I don't think I did....

**Comment by fessehaeve** [comment]
@brdandu closed via some work or deemed not wanted anymore? It would be nice to have some info.

**Comment by fessehaeve** [comment]
Never mind, I see on the right side there is a section for that. Thanks.
