### ISSUE TITLE
Attributes table is broken

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#392]
the ZAP UI is completely broken?  In the sense that I can't turn on an attribute I added to the XML.
```
(node:29625) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
⇝ (node:29625) UnhandledPromiseRejectionWarning: ReferenceError: isValidSignedNumberString is not defined
    at validateSpecificAttribute (/Users/bzbarsky/connectedhomeip/third_party/zap/repo/src-electron/validation/validation.js:79:7)
    at Object.validateAttribute (/Users/bzbarsky/connectedhomeip/third_party/zap/repo/src-electron/validation/validation.js:38:10)
    at /Users/bzbarsky/connectedhomeip/third_party/zap/repo/src-electron/rest/user-data.js:210:26
```

**Comment by tecimovic** [comment]
I've retested this, and it seems to work now. @bzbarsky-apple : this should resolve your problem with attribute page.

(Note: there is another bug: https://github.com/project-chip/zap/issues/311 which lists some additional issues with attribute page, but as of now, it's at least somewhat usable.)

**Comment by bzbarsky-apple** [comment]
Not fixed with the following steps:

1. Check out Matter rev 0902641677380ec86822fe69cdaa299849d24564
2. Go into `third_party/zap/repo`
3. `git checkout master`
4. `git pull upstream master`
5. `git checkout 42c158dfc7cd42f9071962619ca49aba5141ebc7`
6. Go back into the Matter toplevel
7. `git add third_party`
8. `./scripts/tools/zap/run_zaptool.sh examples/all-clusters-app/all-clusters-common/all-clusters-app.zap`
9. In the ZAP UI, select endpoint 1.
10. Filter for the "Test Cluster" cluster.
11. Click the gear icon for it.
12. On the attributes tab, click the "Enabled" switch next to the first attribute (id -= 0, name == boolean).

The attribute does not switch to disabled in the UI.

Now if I got back to the endpoint view and then back into the "Test Cluster" configuration, the attribute _does_ show as disabled.  And at that point I can toggle it and other attriibutes and they work fine.  But the first time the attributes view loads it's pretty broken...
