### ISSUE TITLE
Events are not saved to .zap after being enabled in zap GUI

### ISSUE THREAD

**Issue by mykrupp** [project-chip/zap#461]
#### Problem
Zap events are not being written to .zap file after enabling the events in the GUI.

My process:
./scripts/tools/zap/run_zaptool.sh
open .zap file in GUI
enable desired events
save .zap file in GUI

I notice that the build timestamp of the .zap file is updated to current time. I am able to add clusters and attributes properly, but not events. 

When I open the .zap file again, the events are back in an unchecked state. Generating from the zap file does not add the event to the zzz-generated file.

 #### Proposed Solution
 Determine why events are not saved properly to .zap file after being enabled in the zap GUI

**Comment by tecimovic** [comment]
**How this should work**

Functionally, I don't know of anything else with events, except enabling and disabling them. There seems to be a "Required" field with the events. So I think functionally this should work like this:
1. Events are listed in the UI, same way as they are now.
2. The ones that are "Required" show selected by default. Users can unselect them, but they get a yellow triangle warning, same way as if you unselect a required command or attribute.
3. The ones that are not required, show unselected by default. Users can select them.

Then these choices, obviously, have to be saved into the .zap file. So saving and reloading ends you in the same spot.

We also have to deal with fact that ZigbeePro doesn't have events. So there should be a flag somewhere, data-driven from zcl.json, that determines if "Events" tab in the UI should even be visible.

**Technical work**

1. There is already ENDPOINT_TYPE_EVENT table which should be recording the states of "inclusion", true/false. We need to properly tie up the UI with that table. We need to properly tie up the writing of the .zap file, and the reading back in. I suspect somewhere in this process the code simply drops the ball, because it was never 100% implemented.
2. We need to properly implement the UI logic with the yellow warning triangles.
3. We should use standard package options to determine the existence of the UI tab, based on the toplevel zcl package.
4. Review the helpers and make sure the helpers are properly sensitive to user configuration and templates can be written that cover the enabled/disabled events.

**Some questions**

1. There is no DEVICE_TYPE_EVENT, so we can't add events to device types. Do we need this?
2. Does anyone know of any other user-driven control around events, except enabling/disabling the non-required ones?

**Comment by tecimovic** [comment]
@bzbarsky-apple @vivien-apple @mrjerryjohns @tcarmelveilleux :
   there is some lack of functionality around "events", simply because we dropped the ball on this at some point, given that the static data was really all that was needed, and user-configurable data was not yet at the top of the priority list.

Can some of you please look at my previous comment and comment if we're missing something around the events, that I don't know needs to happen?

**Comment by bzbarsky-apple** [comment]
There may be feature-map dependence for events.  Other than that, mostly just enable-disable and being able to get that state from the database...
