### ISSUE TITLE
Failure to generate is silent

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/zap#468]
Someone just reported that on running out of memory their generation did this:
```
🕐 File loading time: 395ms
👎 Program node exited with error code: null
```
and then silently proceeded instead of erroring out.

Looking at the code, this looks like logging from `executeCmd` in `script-util.js` which has this:
```
    let c = spawn(cmd, args)
    c.on('exit', (code) => {
      if (code == 0) resolve(ctx)
      else {
        console.log(`👎 Program ${cmd} exited with error code: ${code}`)
        reject(code)
      }
    })
```
and the presumed caller here is `zap-generate.js`, which has:
```
scriptUtil
  .stampVersion()
  .then(() => scriptUtil.rebuildBackendIfNeeded())
  .then(() => scriptUtil.executeCmd(ctx, 'node', cli))
  .then(() => {
    scriptUtil.doneStamp(startTime)
    process.exit(0)
  })
  .catch((code) => {
    process.exit(code)
  })
```
So presumably this ends up doing `process.exit(null)`, which I am guessing coerces null to a number, which would be 0, which is success.

We need to either figure out why `spawn` is handing out `null` as an error code and fix that, or convert `null` to some nonzero code in our `on('exit')` handler.  We can't have silent failures to generate like this; it causes a huge amount of wasted time.

@tecimovic

**Comment by bzbarsky-apple** [comment]
The docs at https://nodejs.org/api/child_process.html#child_process_event_exit (which I assume are relevant here) say that there are _two_ args passed to an exit handler: `code` and `signal`.  One or the other can be null.  The `code` is if the process exited on its own; the `signal` is if it was terminated by signal (as in this case, running out of memory).

**Comment by jmeg-sfy** [comment]
To add some context this silent error was coming (seems to) from the size allocated for node.

Few months ago i also ran into mem issues but with a backtrace/dump and solve those by doing 
export NODE_OPTIONS="--max-old-space-size=5120"

If that can help to figure out the issue...

Here below this dump 
`022-02-25 16:59:46,989 root INFO    Found test target chip-tool (via examples/chip-tool/templates/tests/templates.json)
2022-02-25 16:59:46,990 root INFO    Generating target: ./scripts/tools/zap/generate.py src/controller/data_model/controller-clusters.zap -t examples/chip-tool/templates/tests/templates.json -o zzz_generated/chip-tool/zap-generated
🚀 Executing: git log -1 --format={"hash": "%H","timestamp": %ct}
🔍 Git commit: aeaa21a71496f3c002e3781b68964fb09d1fa3fc from Fri Feb 04 2022 03:21:40 GMT+0100 (Central European Standard Time)
🚀 Executing: npm run build-backend
> zap@2022.2.4 build-backend /home/jo/DEV/CHIP_MASTER/connectedhomeip/third_party/zap/repo
> npx tsc --build ./tsconfig.json
🚀 Executing: node dist/src-electron/main-process/electron-main.js generate --noUi --noServer --stateDirectory ~/.zap --zcl /home/jo/DEV/CHIP_MASTER/connectedhomeip/src/app/zap-templates/zcl/zcl.json --generationTemplate /home/jo/DEV/CHIP_MASTER/connectedhomeip/examples/chip-tool/templates/tests/templates.json --out /home/jo/DEV/CHIP_MASTER/connectedhomeip/zzz_generated/chip-tool/zap-generated /home/jo/DEV/CHIP_MASTER/connectedhomeip/src/controller/data_model/controller-clusters.zap
🤖 ZAP generation started: 
    🔍 input files: /home/jo/DEV/CHIP_MASTER/connectedhomeip/src/controller/data_model/controller-clusters.zap
    🔍 output pattern: /home/jo/DEV/CHIP_MASTER/connectedhomeip/zzz_generated/chip-tool/zap-generated
    🔍 using templates: /home/jo/DEV/CHIP_MASTER/connectedhomeip/examples/chip-tool/templates/tests/templates.json
    🔍 using zcl data: /home/jo/DEV/CHIP_MASTER/connectedhomeip/src/app/zap-templates/zcl/zcl.json
    🔍 zap version: ver. 2022.2.4, featureLevel 67, commit: aeaa21a71496f3c002e3781b68964fb09d1fa3fc from 2022-02-04T02:21:40.000Z
🕐 Setup time: 1s 104ms 
👉 using input file: /home/jo/DEV/CHIP_MASTER/connectedhomeip/src/controller/data_model/controller-clusters.zap
👉 using output destination: /home/jo/DEV/CHIP_MASTER/connectedhomeip/zzz_generated/chip-tool/zap-generated
🕐 File loading time: 356ms
⇝ 
<--- Last few GCs --->
[112106:0x4c846f0]    22976 ms: Mark-sweep (reduce) 2046.9 (2052.7) -> 2046.7 (2054.4) MB, 1308.1 / 0.0 ms  (average mu = 0.099, current mu = 0.002) allocation failure scavenge might not succeed
[112106:0x4c846f0]    24316 ms: Mark-sweep (reduce) 2047.7 (2056.4) -> 2047.6 (2057.4) MB, 1207.2 / 0.0 ms  (+ 131.2 ms in 16 steps since start of marking, biggest step 74.5 ms, walltime since start of marking 1340 ms) (average mu = 0.051, current mu = 0.
<--- JS stacktrace --->
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
⇝  1: 0xa04200 node::Abort() [node]
⇝  2: 0x94e4e9 node::FatalError(char const*, char const*) [node]
⇝  3: 0xb7978e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
⇝  4: 0xb79b07 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
⇝  5: 0xd34395  [node]
⇝  6: 0xd34f1f  [node]
⇝  7: 0xd42fab v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
⇝  8: 0xd46b6c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
⇝  9: 0xd1524b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
⇝ 10: 0x105b23f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
⇝ 11: 0x1401219  [node]
👎 Program node exited with error code: null`

**Comment by vivien-apple** [comment]
At the moment we probably need to increase the value at https://github.com/project-chip/connectedhomeip/blob/2358a9a7f4add4354ee8636457d7cf7d65f1f735/scripts/tools/zap/generate.py#L193 t something like `16384`.

I tend to think that a bit part of the memory allocation issue is from the YAML test template - I have a patch that should reduce it drastically but this not going to be this week...
