### ISSUE TITLE
Zip packages are packaged in an ugly way

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#722]
When I click on any of the `*.zip` packages in the actions artifacts, I notice the following:
   1.) The files are zipped twice. I unzip it, and get an actual zip.
   2.) The actual zip that I get after unzipping the secondary zip, is a zip bomb. It simply blows up into a bunch of files in the current directly. We should package these files in a way where it unzips into a subdirectory: `zap_VERSION` where version is the current YYYY.MM.DD version format that we use.

**Comment by jingteng25742** [comment]
Github zip all artifacts via its "upload-artifact" action. However it doesn't handle symlinks at all, which prevents us from providing a folder and results in a gigantic .zip file. With those limitations in mind, there isn't really much we can do.

For unzip folder structure, I'd rather not do so because the parsing of the names will be a nightmare for the CI jobs.
