### ISSUE TITLE
[Cluster extension] Enabled custom attribute not loaded

### ISSUE THREAD

**Issue by mauro-girotto** [project-chip/zap#770]
When custom attributes are enabled, all these attributes are set disabled when the zap project is loaded.  I'm using version 2022.10.18.

To replicate:

1. Create a test.xml file with a single attribute:
```xml
<?xml version="1.0" encoding="UTF-8"?>

<configurator>

  <domain name="4Noks" />

  <clusterExtension code="0x0000">

    <attribute
      side="server"
      code="0xFC00"
      define="BOOTLOADER_VERSION_STRING"
      type="CHAR_STRING"
      length="32"
      writable="false"
      default=""
      optional="true"
      manufacturerCode="0x1071"
      >Bootloader Firmware Version</attribute>

  </clusterExtension>

</configurator>
```
2. Add test.xml to ZCL Extensions
3. Enable the attribute (Basic cluster, attribute FC00)
4. Save the zap project: in the .zap file the custom attribute is successfully saved
5. Reopen zap e load the project: the custom attribute is disabled

**Comment by tecimovic** [comment]
Yeah, this was a plain old bug.

When loading in the zap file with the custom XML, if the package was ALREADY loaded from before, it would not link properly. Therefore this did work correctly if you erase the `~/.zap` state directory, since in that case the package would be LOADED and LINKED, but if it was there already, the LINKAGE failed.

I've just pushed a PR that fixed this and I've linked this issue to the PR.
