### ISSUE TITLE
Fix "Electron" naming in the Mac menu

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#784]
When running Zap on a Mac (via npm run zap for sure, I haven't tested a binary build), the first top menu item is titled "Electron". If you open that menu, the final entry is "Quit Electron".

Can we fix that so it says "Zap" and "Quit zap"?

I'd like to weed out the term "Electron" from there, and I have no idea where it's coming from, really.

**Comment by aspecter** [comment]
In the released and self-built version these labels are okay.
In development mode - _npm run zap_ - we cannot change the application menu item label easily, because it is determined by the [application's property file](https://www.electronjs.org/docs/latest/api/menu#main-menus-name), "Quit Electron" could be replaced easily, but it is more elegant if it just follows the application name and the packager or builder solves that like in the application menu case.
